# Generated by Django 4.2.20 on 2025-04-16 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='client_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='client_secret',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='token_uri',
            field=models.TextField(),
        ),
    ]
