# Generated by Django 4.2.20 on 2025-04-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0003_alter_usercredentials_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIleTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_uuid', models.CharField(max_length=50, unique=True)),
                ('source_folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('transferred_files', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driveapp.usercredentials')),
            ],
        ),
    ]
