# Generated by Django 4.2.20 on 2025-06-19 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driveapp', '0007_filetransfer_current_file_transferlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('export_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPrivacyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_consent', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('data_retention_days', models.IntegerField(default=90)),
                ('share_usage_stats', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usercredentials',
            old_name='access_token',
            new_name='encrypted_credentials',
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='usercredentials',
            unique_together={('user', 'user_email')},
        ),
        migrations.AddIndex(
            model_name='usercredentials',
            index=models.Index(fields=['user', 'is_active'], name='driveapp_us_user_id_8de03e_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredentials',
            index=models.Index(fields=['expires_at'], name='driveapp_us_expires_d91e3a_idx'),
        ),
        migrations.AddField(
            model_name='userprivacypreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataexportrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='scopes',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='token_uri',
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['timestamp', 'severity'], name='driveapp_se_timesta_fc6a66_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['event_type'], name='driveapp_se_event_t_2f9013_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user', 'timestamp'], name='driveapp_se_user_id_b6285b_idx'),
        ),
    ]
