# Generated by Django 4.2.20 on 2025-06-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0008_dataexportrequest_securitylog_userprivacypreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='photos_album_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='photos_date_filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='transfer_type',
            field=models.CharField(choices=[('drive', 'Google Drive'), ('photos', 'Google Photos')], default='drive', max_length=20),
        ),
    ]
